### PR TITLE
UIBULKED-426 Query String Display  After Query Builder Closes

### PR DESCRIPTION
**Pull request by vashjs**
After this PR merged fqlQuery will be replaces with user-friendly variant of query which will be show on bulk edit preview page. Ref [UIBULKED-426](https://folio-org.atlassian.net/browse/UIBULKED-426)

### CODE REVIEW

**Review by Terala-Priyanka — CHANGES_REQUESTED** [review]
Please fix the lint issues.

Also looks like there are several such lint issues in the module. Could you please create a ticket and fix them too?

**Review by UladzislauKutarkin — APPROVED** [review]

**Comment by vashjs** [comment]
> Please fix the lint issues.
> 
> Also looks like there are several such lint issues in the module. Could you please create a ticket and fix them too?

Hi @Terala-Priyanka, eslint issue for current ticket was fixed. About all other issues - ticket was created https://folio-org.atlassian.net/browse/UIBULKED-454

**Review by Terala-Priyanka — APPROVED** [review]

**Comment by Terala-Priyanka** [comment]
@vashjs Please enhance the code coverage

**Review by Terala-Priyanka — CHANGES_REQUESTED** [review]
Please enhance code coverage.
Also, isn't the new entry in changelog.md appended to what is currently in progress?

**Comment by NikitaSedyx** [comment]
@Terala-Priyanka what is the difference where to put change log line?

**Comment by Terala-Priyanka** [comment]
> @Terala-Priyanka what is the difference where to put change log line?

@NikitaSedyx 
technically or functionally, it will not make any difference. As far as I know, the general practice within Folio is to always append the latest one. It is better to maintain consistency, unless there is any exceptional case adopted in any module.

**Comment by NikitaSedyx** [comment]
@Terala-Priyanka there is no general practice, there are teams that add changelogs doing a release and order is random, our PR checklist says that changelog record should be added, but it doesn't really matter in this case (when 2 other small PRs were merged before) as it doesn't change logical change sequence

**Comment by Terala-Priyanka** [comment]
> @Terala-Priyanka there is no general practice, there are teams that add changelogs doing a release and order is random, our PR checklist says that changelog record should be added, but it doesn't really matter in this case (when 2 other small PRs were merged before) as it doesn't change logical change sequence

Well, it may not have been recorded somewhere as practice, but as it is being added in the scope of this PR, I have suggested it to maintain consistency. But if you do not prefer it, it is up to you.

**Comment by NikitaSedyx** [comment]
I'm just pointing that it can not be pointed as a reason of change request (I understand that you request coverage as well, but only coverage can be a reason to request changes)

**Review by Terala-Priyanka — APPROVED** [review]

**Pull request merged**
